//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/NEW/01 - Player/Player_Input_Manager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Player_Input_Manager: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Player_Input_Manager()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player_Input_Manager"",
    ""maps"": [
        {
            ""name"": ""Player_Action_Map"",
            ""id"": ""007e414a-7fa0-42e0-b2f3-6978a3e3f6a9"",
            ""actions"": [
                {
                    ""name"": ""Input_Normal_Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d8a21885-5e44-4424-98a3-a299a943de49"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Input_Button_1"",
                    ""type"": ""Button"",
                    ""id"": ""dc3011e2-cbb6-4f8c-9b43-16446a75a30d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap,Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Input_Button_2"",
                    ""type"": ""Button"",
                    ""id"": ""485e707e-1490-4ca4-9174-5396ae8d3579"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap,Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Input_Button_3"",
                    ""type"": ""Button"",
                    ""id"": ""5a1dd0ec-ee8e-4cbb-9946-88156a09878a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Input_Button_4"",
                    ""type"": ""Button"",
                    ""id"": ""7aaedce6-90d7-443d-a33f-e155afc8a623"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Tap,Hold"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Input_Trigger_1"",
                    ""type"": ""Button"",
                    ""id"": ""1614e505-a931-4079-843b-2eb7a14ce334"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Input_Trigger_2"",
                    ""type"": ""Button"",
                    ""id"": ""1d05953d-c24b-4082-8ba9-d5298368835d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0c3b0889-79b0-4706-83ce-28f98c9e8dd9"",
                    ""path"": ""<HID::Core (Plus) Wired Controller>/button4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Button_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9d9e17bf-3586-4895-8d16-9fa0dbed66a4"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Button_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc73dabe-d8c8-48ac-b1dc-087a2433ffd8"",
                    ""path"": ""<HID::Core (Plus) Wired Controller>/button3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Button_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f22add3-2836-40d1-87df-222272b7840e"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Button_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24a290c0-610e-4f05-9693-a937062be0e8"",
                    ""path"": ""<Joystick>/trigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Button_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9b992b0-c917-4404-aa95-2e7192069ed4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Button_4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e9af3df8-8f40-4962-bab4-fdaad6dae2e5"",
                    ""path"": ""<HID::Core (Plus) Wired Controller>/button2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Button_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c0069358-95e5-42e6-9457-20e0b2f69dbd"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Button_3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d2dbea10-a44e-4d07-8d28-5510045e3e5d"",
                    ""path"": ""<HID::Core (Plus) Wired Controller>/button5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Trigger_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e6075320-6d32-49d5-b2ee-cf843fffacfa"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Trigger_1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f2a7c986-ffc5-471b-b7c3-ba20cde05d53"",
                    ""path"": ""<HID::Core (Plus) Wired Controller>/button6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Trigger_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a0438b3-7009-499f-9488-8e2e9179005b"",
                    ""path"": ""<Keyboard>/leftShift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Trigger_2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector Control"",
                    ""id"": ""a28b0e43-5316-477b-a6f9-56c1626a6643"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f94fb36d-8345-41d8-a639-f2121587f108"",
                    ""path"": ""<Joystick>/stick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""cc97c1ce-e67f-4bff-987e-95985101acf3"",
                    ""path"": ""<Joystick>/stick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""38e0c5c8-5a10-4e27-a49e-8af4b912ec75"",
                    ""path"": ""<Joystick>/stick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""93f1f77c-5a03-420a-bec2-15900ac33c88"",
                    ""path"": ""<Joystick>/stick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Control"",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector Keyboard"",
                    ""id"": ""657c396b-61f5-4956-86c8-ea252cc3caa6"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0412eaf9-83ed-4f1a-bf55-8ff6a38268cf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9becde41-6867-4ba4-8b6d-95db5cee6990"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""37a4e59c-74ae-4a3d-b5d6-6c2266e81a58"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""3a3c30aa-e914-42aa-acdb-4e9abedec58b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard"",
                    ""action"": ""Input_Normal_Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Control"",
            ""bindingGroup"": ""Control"",
            ""devices"": [
                {
                    ""devicePath"": ""<Joystick>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Keyboard"",
            ""bindingGroup"": ""Keyboard"",
            ""devices"": []
        }
    ]
}");
        // Player_Action_Map
        m_Player_Action_Map = asset.FindActionMap("Player_Action_Map", throwIfNotFound: true);
        m_Player_Action_Map_Input_Normal_Movement = m_Player_Action_Map.FindAction("Input_Normal_Movement", throwIfNotFound: true);
        m_Player_Action_Map_Input_Button_1 = m_Player_Action_Map.FindAction("Input_Button_1", throwIfNotFound: true);
        m_Player_Action_Map_Input_Button_2 = m_Player_Action_Map.FindAction("Input_Button_2", throwIfNotFound: true);
        m_Player_Action_Map_Input_Button_3 = m_Player_Action_Map.FindAction("Input_Button_3", throwIfNotFound: true);
        m_Player_Action_Map_Input_Button_4 = m_Player_Action_Map.FindAction("Input_Button_4", throwIfNotFound: true);
        m_Player_Action_Map_Input_Trigger_1 = m_Player_Action_Map.FindAction("Input_Trigger_1", throwIfNotFound: true);
        m_Player_Action_Map_Input_Trigger_2 = m_Player_Action_Map.FindAction("Input_Trigger_2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player_Action_Map
    private readonly InputActionMap m_Player_Action_Map;
    private List<IPlayer_Action_MapActions> m_Player_Action_MapActionsCallbackInterfaces = new List<IPlayer_Action_MapActions>();
    private readonly InputAction m_Player_Action_Map_Input_Normal_Movement;
    private readonly InputAction m_Player_Action_Map_Input_Button_1;
    private readonly InputAction m_Player_Action_Map_Input_Button_2;
    private readonly InputAction m_Player_Action_Map_Input_Button_3;
    private readonly InputAction m_Player_Action_Map_Input_Button_4;
    private readonly InputAction m_Player_Action_Map_Input_Trigger_1;
    private readonly InputAction m_Player_Action_Map_Input_Trigger_2;
    public struct Player_Action_MapActions
    {
        private @Player_Input_Manager m_Wrapper;
        public Player_Action_MapActions(@Player_Input_Manager wrapper) { m_Wrapper = wrapper; }
        public InputAction @Input_Normal_Movement => m_Wrapper.m_Player_Action_Map_Input_Normal_Movement;
        public InputAction @Input_Button_1 => m_Wrapper.m_Player_Action_Map_Input_Button_1;
        public InputAction @Input_Button_2 => m_Wrapper.m_Player_Action_Map_Input_Button_2;
        public InputAction @Input_Button_3 => m_Wrapper.m_Player_Action_Map_Input_Button_3;
        public InputAction @Input_Button_4 => m_Wrapper.m_Player_Action_Map_Input_Button_4;
        public InputAction @Input_Trigger_1 => m_Wrapper.m_Player_Action_Map_Input_Trigger_1;
        public InputAction @Input_Trigger_2 => m_Wrapper.m_Player_Action_Map_Input_Trigger_2;
        public InputActionMap Get() { return m_Wrapper.m_Player_Action_Map; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(Player_Action_MapActions set) { return set.Get(); }
        public void AddCallbacks(IPlayer_Action_MapActions instance)
        {
            if (instance == null || m_Wrapper.m_Player_Action_MapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Player_Action_MapActionsCallbackInterfaces.Add(instance);
            @Input_Normal_Movement.started += instance.OnInput_Normal_Movement;
            @Input_Normal_Movement.performed += instance.OnInput_Normal_Movement;
            @Input_Normal_Movement.canceled += instance.OnInput_Normal_Movement;
            @Input_Button_1.started += instance.OnInput_Button_1;
            @Input_Button_1.performed += instance.OnInput_Button_1;
            @Input_Button_1.canceled += instance.OnInput_Button_1;
            @Input_Button_2.started += instance.OnInput_Button_2;
            @Input_Button_2.performed += instance.OnInput_Button_2;
            @Input_Button_2.canceled += instance.OnInput_Button_2;
            @Input_Button_3.started += instance.OnInput_Button_3;
            @Input_Button_3.performed += instance.OnInput_Button_3;
            @Input_Button_3.canceled += instance.OnInput_Button_3;
            @Input_Button_4.started += instance.OnInput_Button_4;
            @Input_Button_4.performed += instance.OnInput_Button_4;
            @Input_Button_4.canceled += instance.OnInput_Button_4;
            @Input_Trigger_1.started += instance.OnInput_Trigger_1;
            @Input_Trigger_1.performed += instance.OnInput_Trigger_1;
            @Input_Trigger_1.canceled += instance.OnInput_Trigger_1;
            @Input_Trigger_2.started += instance.OnInput_Trigger_2;
            @Input_Trigger_2.performed += instance.OnInput_Trigger_2;
            @Input_Trigger_2.canceled += instance.OnInput_Trigger_2;
        }

        private void UnregisterCallbacks(IPlayer_Action_MapActions instance)
        {
            @Input_Normal_Movement.started -= instance.OnInput_Normal_Movement;
            @Input_Normal_Movement.performed -= instance.OnInput_Normal_Movement;
            @Input_Normal_Movement.canceled -= instance.OnInput_Normal_Movement;
            @Input_Button_1.started -= instance.OnInput_Button_1;
            @Input_Button_1.performed -= instance.OnInput_Button_1;
            @Input_Button_1.canceled -= instance.OnInput_Button_1;
            @Input_Button_2.started -= instance.OnInput_Button_2;
            @Input_Button_2.performed -= instance.OnInput_Button_2;
            @Input_Button_2.canceled -= instance.OnInput_Button_2;
            @Input_Button_3.started -= instance.OnInput_Button_3;
            @Input_Button_3.performed -= instance.OnInput_Button_3;
            @Input_Button_3.canceled -= instance.OnInput_Button_3;
            @Input_Button_4.started -= instance.OnInput_Button_4;
            @Input_Button_4.performed -= instance.OnInput_Button_4;
            @Input_Button_4.canceled -= instance.OnInput_Button_4;
            @Input_Trigger_1.started -= instance.OnInput_Trigger_1;
            @Input_Trigger_1.performed -= instance.OnInput_Trigger_1;
            @Input_Trigger_1.canceled -= instance.OnInput_Trigger_1;
            @Input_Trigger_2.started -= instance.OnInput_Trigger_2;
            @Input_Trigger_2.performed -= instance.OnInput_Trigger_2;
            @Input_Trigger_2.canceled -= instance.OnInput_Trigger_2;
        }

        public void RemoveCallbacks(IPlayer_Action_MapActions instance)
        {
            if (m_Wrapper.m_Player_Action_MapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayer_Action_MapActions instance)
        {
            foreach (var item in m_Wrapper.m_Player_Action_MapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Player_Action_MapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public Player_Action_MapActions @Player_Action_Map => new Player_Action_MapActions(this);
    private int m_ControlSchemeIndex = -1;
    public InputControlScheme ControlScheme
    {
        get
        {
            if (m_ControlSchemeIndex == -1) m_ControlSchemeIndex = asset.FindControlSchemeIndex("Control");
            return asset.controlSchemes[m_ControlSchemeIndex];
        }
    }
    private int m_KeyboardSchemeIndex = -1;
    public InputControlScheme KeyboardScheme
    {
        get
        {
            if (m_KeyboardSchemeIndex == -1) m_KeyboardSchemeIndex = asset.FindControlSchemeIndex("Keyboard");
            return asset.controlSchemes[m_KeyboardSchemeIndex];
        }
    }
    public interface IPlayer_Action_MapActions
    {
        void OnInput_Normal_Movement(InputAction.CallbackContext context);
        void OnInput_Button_1(InputAction.CallbackContext context);
        void OnInput_Button_2(InputAction.CallbackContext context);
        void OnInput_Button_3(InputAction.CallbackContext context);
        void OnInput_Button_4(InputAction.CallbackContext context);
        void OnInput_Trigger_1(InputAction.CallbackContext context);
        void OnInput_Trigger_2(InputAction.CallbackContext context);
    }
}
